# Site settings
title: Somewhere in the tubes
email: contact@achals.com
description: > # this means to ignore newlines until "baseurl:"
    Achal Shah's personal webpage and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://achals.com" # the base hostname & protocol for your site
twitter_username: achals
github_username:  achals

# Build settings
markdown: kramdown
